# Generated by Django 5.2.4 on 2026-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/%Y/%m/"
                    ),
                ),
                ("question", models.TextField(blank=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("identify", "Identify the machine"),
                            ("components", "Components & their roles"),
                            ("function", "How it works"),
                            ("troubleshoot", "Troubleshoot a problem"),
                        ],
                        default="identify",
                        max_length=20,
                    ),
                ),
                ("equipment_name", models.CharField(blank=True, max_length=200)),
                ("response_md", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
