# Generated by Django 5.2.4 on 2026-07-04 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysis",
            name="image",
        ),
    ]
