# Generated by Django 5.2.4 on 2026-07-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0002_remove_analysis_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="level",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("technician", "Technician"),
                    ("senior", "Senior engineer"),
                ],
                default="technician",
                max_length=12,
            ),
        ),
    ]
