# Generated by Django 5.2.4 on 2026-07-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0003_analysis_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="mode",
            field=models.CharField(
                choices=[
                    ("identify", "Identify the machine"),
                    ("components", "Components & their roles"),
                    ("board", "Board / PCB components"),
                    ("function", "How it works"),
                    ("troubleshoot", "Troubleshoot a problem"),
                ],
                default="identify",
                max_length=20,
            ),
        ),
    ]
